apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maas-praxis-system
resources:
  - ../models-as-a-service/deployment/base/maas-controller/default
configMapGenerator:
  - name: maas-parameters
    behavior: merge
    envs:
      - params.env
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      kind: Deployment
      name: maas-controller
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/opendatahub/maas-controller:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: maas-praxis-gateway
