#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Gateway-to-Gateway Routing E2E Demo — Transcript Generator
#
# Generates a Markdown transcript of the complete gateway-to-gateway demo.
#
# Usage:
#   bash run-complete-e2e-demo.sh [output-file]
#
# Environment variables (optional):
#   PRAXIS_BIN       Path to a Praxis binary built from
#                    nerdalert/praxis:praxis-multi-cluster-poc-v1
#   PRAXIS_WORKTREE  Praxis checkout used to find target/debug/praxis or
#                    target/release/praxis when PRAXIS_BIN is unset
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${1:-$SCRIPT_DIR/demo-output.md}"
WORK="$(mktemp -d)"

cleanup() {
  bash "$SCRIPT_DIR/scripts/cleanup.sh" >/dev/null 2>&1 || true
  rm -rf "$WORK"
}

trap cleanup EXIT

run_step() {
  local title="$1"
  shift
  local log="$WORK/${title//[^A-Za-z0-9_]/_}.log"

  {
    echo
    echo "---"
    echo
    echo "## $title"
    echo
    echo '```bash'
    printf '%q ' "$@"
    echo
    echo '```'
    echo
    echo '```text'
  } >>"$OUT"

  set +e
  "$@" 2>&1 | tee "$log"
  local status="${PIPESTATUS[0]}"
  set -e

  {
    cat "$log"
    echo '```'
    echo
    echo "Exit status: \`$status\`"
  } >>"$OUT"

  if [[ "$status" -ne 0 ]]; then
    echo "ERROR: step failed: $title" >&2
    exit "$status"
  fi
}

mkdir -p "$(dirname "$OUT")"

cat >"$OUT" <<EOF
# Gateway-to-Gateway Routing E2E Demo Transcript

Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

This transcript was generated by:

\`\`\`bash
bash run-complete-e2e-demo.sh
\`\`\`

## Demo purpose

This demo validates the Praxis gateway-to-gateway foundation for
praxis-proxy/praxis#664 before upstream production PRs are split.

It proves a three-gateway topology with:

- mTLS gateway identity;
- destination-side ingress trust;
- static site/capability routing records;
- local and remote inference routing;
- deterministic freshness/locality assertions from the POC;
- MCP tool routing through the gateway-to-gateway path; and
- an explicit A2A skip because A2A routing remains deferred.

## Architecture summary

\`\`\`text
client
  -> site-a Praxis public listener
       -> local backend, or
       -> mTLS to site-b/site-c grid listener
            -> destination ingress trust
            -> destination local backend
\`\`\`

Request routing reads local validated state. The request does not query an
Operator, SWIM, Kubernetes, Prometheus, or a database while routing. Future
control-plane work may update snapshots in the background.

## Source branches

| Source | Reference |
| --- | --- |
| Praxis POC branch | https://github.com/nerdalert/praxis/tree/praxis-multi-cluster-poc-v1 |
| Spike demo package | https://github.com/nerdalert/praxis-research-spikes/tree/main/demo/gateway-to-gateway-routing |

## Presenter guide

Use \`demo-narrative.md\` as the presenter script. This generated transcript is
the command/output artifact for review and repeatability.

EOF

echo "Generating gateway-to-gateway demo transcript: $OUT"

run_step "Cleanup before run" bash "$SCRIPT_DIR/scripts/cleanup.sh"
run_step "Prerequisite check" bash "$SCRIPT_DIR/scripts/check-prereqs.sh"
run_step "Generate demo certificates" bash "$SCRIPT_DIR/scripts/generate-certs.sh"
run_step "Run gateway-to-gateway assertions" bash "$SCRIPT_DIR/scripts/run-demo.sh"
run_step "Cleanup after run" bash "$SCRIPT_DIR/scripts/cleanup.sh"

cat >>"$OUT" <<'EOF'

---

## Expected result

The assertion step should end with:

```text
Passed:              29
Failed:              0
Not implemented yet: 1

RESULT: PASS (all implemented assertions passed)
```

The single expected skip is A2A gateway routing. It is intentionally deferred
because MCP route metadata was validated first, while A2A still needs explicit
route-key semantics, session/task expectations, and gateway tests. It must not
be claimed as implemented.
EOF

echo "Transcript written to: $OUT"
