#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# llm-d Native AI Gateway -- Complete E2E Demo
#
# Creates a KIND cluster, builds and loads images, runs all 9 examples,
# captures output to sample-output.md, and cleans up.
#
# Usage:
#   bash run-complete-e2e-demo.sh [output-file]
#
# Environment variables (optional):
#   PRAXIS_DIR                Path to the Praxis checkout
#   LLM_D_INFERENCE_SIM_DIR   Path to llm-d-inference-sim
#   KIND_CLUSTER_NAME          KIND cluster name (default: praxis-llmd-demo)
#   PRAXIS_NODE_PORT           NodePort for Praxis (default: 30081)
#   PRAXIS_IMAGE               Praxis container image tag (default: praxis-epp:dev)
#   SIM_IMAGE                  Simulator image tag (default: ghcr.io/llm-d/llm-d-inference-sim:dev)
#   SKIP_CLEANUP               Set to 1 to keep the cluster after the run
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/scripts/common.sh"

OUT="${1:-$SCRIPT_DIR/sample-output.md}"
SKIP_CLEANUP="${SKIP_CLEANUP:-0}"

# -- Per-example result tracking --------------------------------------------
declare -a EXAMPLE_NAMES=()
declare -a EXAMPLE_RESULTS=()
TOTAL_PASS=0
TOTAL_FAIL=0

# ---------------------------------------------------------------------------
# Cleanup handler
# ---------------------------------------------------------------------------

demo_cleanup() {
  if [[ "$SKIP_CLEANUP" == "1" ]]; then
    log "SKIP_CLEANUP=1 -- keeping KIND cluster $KIND_CLUSTER_NAME"
  else
    log "Cleaning up ..."
    bash "$SCRIPT_DIR/scripts/cleanup.sh" --all 2>/dev/null || true
  fi
}

trap demo_cleanup EXIT

# ---------------------------------------------------------------------------
# Transcript helpers
# ---------------------------------------------------------------------------

out_header() {
  {
    echo "# llm-d Native AI Gateway Demo Transcript"
    echo
    echo "Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "This transcript was generated by:"
    echo
    echo '```bash'
    echo "bash run-complete-e2e-demo.sh"
    echo '```'
    echo
  } >"$OUT"
}

out_section() {
  {
    echo
    echo "---"
    echo
    echo "## $1"
    echo
  } >>"$OUT"
}

out_text() {
  echo "$1" >>"$OUT"
}

out_code() {
  local lang="${1:-text}"
  {
    echo
    echo "\`\`\`${lang}"
    cat
    echo
    echo '```'
    echo
  } >>"$OUT"
}

capture_example() {
  local num="$1"
  local title="$2"
  local script="$3"

  log_section "Running Example $num: $title"
  out_section "Example $num: $title"

  # Clean up previous example resources (ignore errors).
  bash "$SCRIPT_DIR/scripts/cleanup.sh" 2>/dev/null || true

  # Run the example script and capture output.
  local output
  local exit_code=0
  output="$(bash "$SCRIPT_DIR/scripts/$script" 2>&1)" || exit_code=$?

  EXAMPLE_NAMES+=("$num: $title")

  if [[ "$exit_code" -eq 0 ]]; then
    out_text "**Status:** PASS"
    EXAMPLE_RESULTS+=("PASS")
    TOTAL_PASS=$((TOTAL_PASS + 1))
  else
    out_text "**Status:** FAIL (exit code $exit_code)"
    EXAMPLE_RESULTS+=("FAIL")
    TOTAL_FAIL=$((TOTAL_FAIL + 1))
  fi

  echo "$output" | out_code "text"
  echo "$output"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

log_section "llm-d Native AI Gateway -- Complete E2E Demo"

# Step 1: Check prerequisites
bash "$SCRIPT_DIR/scripts/check-prereqs.sh"

# Step 2: Create KIND cluster
bash "$SCRIPT_DIR/scripts/create-kind.sh"

# Step 3: Build and load images
bash "$SCRIPT_DIR/scripts/build-and-load-images.sh"

# Step 4: Write transcript header
mkdir -p "$(dirname "$OUT")"
out_header

# Step 5: Run all examples
capture_example 1 "Static Model-Aware Baseline"    "run-static-model-aware.sh"
capture_example 2 "Load-Aware Routing"              "run-load-aware.sh"
capture_example 3 "InferencePool Discovery"         "run-inferencepool-discovery.sh"
capture_example 4 "Gateway API HTTPRoute"           "run-gateway-api.sh"
capture_example 5 "Prefix-Cache-Aware Routing"      "run-prefix-cache.sh"
capture_example 6 "Saturation/Admission Gate"       "run-saturation.sh"
capture_example 7 "P/D Disaggregation"              "run-pd-disaggregation.sh"
capture_example 8 "InferenceModelRewrite"           "run-model-rewrite.sh"
capture_example 9 "InferenceObjective Metadata"     "run-inference-objective.sh"

# Step 6: Summary
out_section "Summary"

{
  echo "| # | Example | Status |"
  echo "|---|---------|--------|"
  for i in "${!EXAMPLE_NAMES[@]}"; do
    echo "| ${EXAMPLE_NAMES[$i]} | ${EXAMPLE_RESULTS[$i]} |"
  done
} >>"$OUT"

log_section "Demo complete"
log "Transcript written to: $OUT"

# Print summary to stdout
echo
echo "================================================================"
echo "  RESULTS SUMMARY"
echo "================================================================"
echo
for i in "${!EXAMPLE_NAMES[@]}"; do
  printf "  %-45s %s\n" "${EXAMPLE_NAMES[$i]}" "${EXAMPLE_RESULTS[$i]}"
done
echo
echo "  Passed: $TOTAL_PASS  Failed: $TOTAL_FAIL  Total: ${#EXAMPLE_NAMES[@]}"
echo "================================================================"
echo

if [[ "$TOTAL_FAIL" -gt 0 ]]; then
  log "ERROR: $TOTAL_FAIL example(s) failed"
  exit 1
fi
